### ISSUE TITLE
使用“代刀中@xxx”时报错。

### ISSUE THREAD

**Issue by hot36952** [sdyxxjj123/Daidao#12]
[2021-10-22 21:26:33,996 daidao] ERROR: <class 'aiocqhttp.exceptions.NetworkError'> occured when kakin handling message 685990.
[2021-10-22 21:26:33,996 daidao] ERROR: WebSocket API call timeout
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\api_impl.py", line 104, in fetch
    return await asyncio.wait_for(future, timeout_sec)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\pcr\Mirai-Bot-Setup\HoshinoBot\hoshino\msghandler.py", line 28, in handle_message
    await sf.func(bot, event)
  File "C:\Users\Administrator\Desktop\pcr\Mirai-Bot-Setup\HoshinoBot\hoshino\modules\daidao\daidao.py", line 552, in kakin
    user_card = await get_user_card(bot, ev.group_id, ev.user_id)
  File "C:\Users\Administrator\Desktop\pcr\Mirai-Bot-Setup\HoshinoBot\hoshino\modules\daidao\daidao.py", line 131, in get_user_card
    mlist = await bot.get_group_member_list(group_id=group_id)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\__init__.py", line 238, in call_action
    return await self._api.call_action(action=action, **params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\api_impl.py", line 178, in call_action
    result = await self._wsr_api.call_action(action, **params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\api_impl.py", line 153, in call_action
    return _handle_api_result(await
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\api_impl.py", line 108, in fetch
    raise NetworkError('WebSocket API call timeout')
aiocqhttp.exceptions.NetworkError: WebSocket API call timeout

**Comment by hot36952** [comment]
@othinus001 请问可以帮帮忙吗

**Comment by sdyxxjj123** [comment]
WebSocket API call timeout请检查URL或CQ端
